const products = [
  {id:1,name:"Golden Halo Ring",price:150,originalPrice:300,sizes:["6","7","8","9","10"],icon:"💍",image:"images/Rings/R01.png",stock:4,category:"RINGS",description:"A timeless ring designed to add a refined golden touch to every look.",material:"Gold plated",size:"Choose your ring size"},
  {id:2,name:"Golden Halo Ring",price:150,originalPrice:300,sizes:["6","7","8","9","10"],icon:"💍",image:"images/Rings/R02.png",stock:4,category:"RINGS",description:"A timeless ring designed to add a refined golden touch to every look.",material:"Gold plated",size:"Choose your ring size"},
  {id:3,name:"Pharaoh Ring",price:150,originalPrice:300,sizes:["6","7","8","9","10"],icon:"💍",image:"images/Rings/R03.jpg",stock:4,category:"RINGS",description:"A timeless ring designed to add a refined golden touch to every look.",material:"Gold plated",size:"Choose your ring size"},

  {id:4,name:"Royal Drop Earrings",price:2400,originalPrice:null,sizes:[],icon:"✦",image:"images/earrings1.jpg",stock:0,category:"EARRINGS",description:"Elegant drop earrings with a graceful silhouette made for special occasions and everyday luxury.",material:"Gold plated",stone:"Crystal",size:"One size"},
  {id:5,name:"Classic Gold Necklace",price:3200,originalPrice:null,sizes:[],icon:"♢",image:"images/Necklace/N01.png",stock:2,category:"NECKLACES",description:"A classic necklace that layers beautifully or stands alone as a sophisticated statement.",material:"Gold plated",stone:"None",size:"Adjustable"},
  {id:6,name:"Classic Gold Necklace",price:3200,originalPrice:null,sizes:[],icon:"♢",image:"images/Necklace/N02.png",stock:2,category:"NECKLACES",description:"A classic necklace that layers beautifully or stands alone as a sophisticated statement.",material:"Gold plated",stone:"None",size:"Adjustable"},
  {id:7,name:"Classic Gold Necklace",price:3200,originalPrice:null,sizes:[],icon:"♢",image:"images/Necklace/N03.png",stock:2,category:"NECKLACES",description:"A classic necklace that layers beautifully or stands alone as a sophisticated statement.",material:"Gold plated",stone:"None",size:"Adjustable"},
  {id:8,name:"Classic Gold Necklace",price:3200,originalPrice:null,sizes:[],icon:"♢",image:"images/Necklace/N04.png",stock:2,category:"NECKLACES",description:"A classic necklace that layers beautifully or stands alone as a sophisticated statement.",material:"Gold plated",stone:"None",size:"Adjustable"},

  {id:9,name:"Luna Bracelet",price:2100,originalPrice:null,sizes:[],icon:"◌",image:"images/bracelet1.jpg",stock:6,category:"BRACELETS",description:"A delicate bracelet inspired by soft curves and subtle shine, perfect for stacking.",material:"Gold plated",stone:"Crystal",size:"Adjustable"},
  {id:10,name:"Royal Emerald Set",price:4900,originalPrice:null,sizes:[],icon:"✿",image:"images/set1.jpg",stock:1,category:"SETS",description:"A statement emerald set combining timeless elegance with a rich royal-inspired character.",material:"Gold plated",stone:"Emerald",size:"Adjustable"}
];
let cart=JSON.parse(localStorage.getItem("hodaShineCart")||"[]");
let wishlist=JSON.parse(localStorage.getItem("hodaShineWishlist")||"[]");
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("en-EG").format(n);
const productsEl=$("products"), cartPanel=$("cartPanel"), cartOverlay=$("cartOverlay"), cartItemsEl=$("cartItems"), cartTotalEl=$("cartTotal"), cartCountEl=$("cartCount");
function save(){localStorage.setItem("hodaShineCart",JSON.stringify(cart));localStorage.setItem("hodaShineWishlist",JSON.stringify(wishlist));renderCart();renderWishlistCount();}
function renderProducts(list=products){productsEl.innerHTML=list.map(p=>{const sold=p.stock<=0, fav=wishlist.includes(p.id); const price=p.originalPrice&&p.originalPrice>p.price?`<span class="old-price">EGP ${money(p.originalPrice)}</span><span class="sale-price">EGP ${money(p.price)}</span>`:`<span class="sale-price">EGP ${money(p.price)}</span>`; return `<article class="product-card ${sold?"sold-card":""}">${sold?'<div class="sold-out">SOLD OUT</div>':""}<button class="wish-product ${fav?"active":""}" onclick="toggleWishlist(${p.id})" aria-label="Wishlist">♡</button><button class="product-image product-click" type="button" onclick="openProduct(${p.id})"><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.parentElement.innerHTML='${p.icon}'"></button><div class="product-info"><button class="product-name-button" onclick="openProduct(${p.id})"><h3>${p.name}</h3></button><div class="price">${price}</div><div class="product-actions"><span>${sold?"Currently unavailable":`${p.stock} available`}</span><button class="add-button" ${sold?"disabled":""} onclick="addToCart(${p.id})">${sold?"SOLD OUT":"ADD TO CART"}</button></div></div></article>`}).join("");}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const sold=p.stock<=0;const old=p.originalPrice&&p.originalPrice>p.price?`<span class="old-price">EGP ${money(p.originalPrice)}</span>`:""; const sizes=p.sizes.length?`<div class="product-option"><label><strong>Ring Size</strong></label><select id="ringSizeSelect" class="ring-size-select"><option value="">Choose a size</option>${p.sizes.map(s=>`<option value="${s}">${s}</option>`).join("")}</select></div>`:""; $("productModalContent").innerHTML=`<div class="product-detail-grid"><div class="product-detail-image"><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.parentElement.innerHTML='<span>${p.icon}</span>'"></div><div class="product-detail-copy"><p class="eyebrow">${p.category}</p><h2>${p.name}</h2><div class="detail-price">${old}<span class="sale-price">EGP ${money(p.price)}</span></div><p class="detail-description">${p.description}</p><div class="product-specs"><div><span>Material</span><strong>${p.material}</strong></<div><span>Size</span><strong>${p.size}</strong></div></div>${sizes}<p class="stock-note">${sold?"Currently unavailable":`${p.stock} available`}</p><button class="gold-button full" ${sold?"disabled":""} onclick="addFromModal(${p.id})">${sold?"SOLD OUT":"ADD TO CART"}</button></div></div>`; $("productModal").classList.add("open");document.body.style.overflow="hidden";}
function addFromModal(id){const p=products.find(x=>x.id===id);const size=$("ringSizeSelect")?.value||null;if(p.sizes.length&&!size){alert("Please choose a ring size first.");return;}addToCart(id,size);closeProduct();}
function closeProduct(){$("productModal").classList.remove("open");$("productModal").setAttribute("aria-hidden","true");if(!cartPanel.classList.contains("open"))document.body.style.overflow="";}
function addToCart(id,size=null){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return;const key=`${id}::${size||""}`;const item=cart.find(x=>x.key===key);if(item){if(item.qty<p.stock)item.qty++;}else cart.push({key,id,qty:1,size});save();openCart();}
function changeQty(key,amount){const item=cart.find(x=>x.key===key);const p=item&&products.find(x=>x.id===item.id);if(!item||!p)return;item.qty+=amount;if(item.qty<=0)cart=cart.filter(x=>x.key!==key);else if(item.qty>p.stock)item.qty=p.stock;save();}
function renderCart(){if(!cart.length){cartItemsEl.innerHTML='<p>Your cart is empty.</p>';cartTotalEl.textContent="Total: EGP 0";cartCountEl.textContent="0";return;}let total=0,count=0;cartItemsEl.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return"";total+=p.price*i.qty;count+=i.qty;return `<div class="cart-item"><div><strong>${p.name}${i.size?` <span class="cart-size">Size ${i.size}</span>`:""}</strong><div>EGP ${money(p.price)} × ${i.qty}</div><div class="qty"><button onclick="changeQty('${i.key}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty('${i.key}',1)">+</button><button onclick="changeQty('${i.key}',-${i.qty})">Remove</button></div></div><strong>EGP ${money(p.price*i.qty)}</strong></div>`}).join("");cartTotalEl.textContent=`Total: EGP ${money(total)}`;cartCountEl.textContent=count;}
function openCart(){$("cartPanel").classList.add("open");$("cartOverlay").classList.add("open");document.body.style.overflow="hidden";}function closeCart(){$("cartPanel").classList.remove("open");$("cartOverlay").classList.remove("open");document.body.style.overflow="";}
function toggleWishlist(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();renderProducts();}
function renderWishlistCount(){$("wishlistCount").textContent=wishlist.length;}
function openWishlist(){const box=$("wishlistItems");box.innerHTML=wishlist.length?wishlist.map(id=>{const p=products.find(x=>x.id===id);return `<button class="wishlist-row" onclick="openProduct(${id});closeWishlist()"><img src="${p.image}" alt=""><span>${p.name}</span><b>EGP ${money(p.price)}</b></button>`}).join(""):'<p class="panel-muted">Your wishlist is empty.</p>';$("wishlistPanel").classList.add("open");$("wishlistPanel").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
function closeWishlist(){$("wishlistPanel").classList.remove("open");$("wishlistPanel").setAttribute("aria-hidden","true");document.body.style.overflow="";}
function openAccount(){$("accountPanel").classList.add("open");$("accountPanel").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}function closeAccount(){$("accountPanel").classList.remove("open");$("accountPanel").setAttribute("aria-hidden","true");document.body.style.overflow="";}
$("closeProduct").addEventListener("click",closeProduct);document.querySelector("[data-close-product]").addEventListener("click",closeProduct);$("cartButton").addEventListener("click",openCart);$("closeCart").addEventListener("click",closeCart);$("cartOverlay").addEventListener("click",closeCart);$("wishlistButton").addEventListener("click",openWishlist);$("closeWishlist").addEventListener("click",closeWishlist);$("accountButton").addEventListener("click",openAccount);$("closeAccount").addEventListener("click",closeAccount);document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeProduct();closeWishlist();closeAccount();}});
$("searchInput").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();renderProducts(products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(q)));});
$("checkoutForm").addEventListener("submit",e=>{e.preventDefault();$("orderMessage").textContent=cart.length?"Demo order received. Later we can connect this form to WhatsApp, Google Sheets, or a real payment system.":"Add a product to the cart first.";});
// Category filter
document.querySelectorAll(".category-card").forEach(card => {
    card.addEventListener("click", function () {
        const category = this.dataset.category;

        const filteredProducts = products.filter(
            product => product.category === category
        );

        renderProducts(filteredProducts);

        document.getElementById("shop").scrollIntoView({
            behavior: "smooth"
        });
    });
});renderProducts();renderCart();renderWishlistCount();
